name: SlabToBloc
version: 1.0
author: indes33

main: fr.indes33.slabtobloc.Main

commands:
  test10:
    description: Ceci est une commande de test
  alerte:
    description: Ceci est une commande d'alerte
  spawnonme:
    description: Ceci est une commande pour faire spawn sur soi un squelette