name: SlabToBloc
version: 1.0
api-version: 1.16
author: indes33

main: fr.indes33.slabtobloc.Main

commands:
  test:
    description: Ceci est une commande de test
  alerte:
    description: Ceci est une commande d'alerte
  spawnonme:
    description: Ceci est une commande pour faire spawn sur soi un squelette
  spawn:
    description: commande pour se tp au spawn du serv
  sethome:
    description: commande pour definir un home
  home:
    description: commande pour se tp a son home
  delhome:
    description: commande pour suprimer un home